[program:robot8_act_dinov3_ddp64]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/robot8_act_dinov3_ddp64.sh
directory=/workspace/2027icra
autostart=false
autorestart=false
startsecs=5
stopasgroup=true
killasgroup=true
stopsignal=INT
stopwaitsecs=180
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
